In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

sns.set()

You can read about the dataset [here](https://archive.ics.uci.edu/ml/datasets/car+evaluation)

In [45]:
df = pd.read_csv(r'C:\Users\Siam Cheema\Downloads\Documents\car.data.txt',header=None)

In [46]:
df.head()

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [47]:
df.columns = ['Buying', 'maintenance', 'doors', 'persons','lug_bot','safety','class']

In [48]:
df.head()

Buying maintenance doors persons lug_bot safety  class
0  vhigh       vhigh     2       2   small    low  unacc
1  vhigh       vhigh     2       2   small    med  unacc
2  vhigh       vhigh     2       2   small   high  unacc
3  vhigh       vhigh     2       2     med    low  unacc
4  vhigh       vhigh     2       2     med    med  unacc

In [49]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [50]:
from sklearn.preprocessing import OneHotEncoder

In [51]:
a1 = pd.get_dummies(df['Buying'], prefix='buy')
a2 = pd.get_dummies(df['maintenance'], prefix='mainte')
a3 = pd.get_dummies(df['doors'], prefix='doors')
a4 = pd.get_dummies(df['persons'], prefix='persons')
a5 = pd.get_dummies(df['lug_bot'], prefix='lug')
a6 = pd.get_dummies(df['safety'], prefix='safety')

In [52]:
df = pd.concat([a1,a2,a3,a4,a5,a6], axis=1)

In [53]:
df.shape

(1728, 21)

In [54]:
print(a1.shape, a2.shape, a3.shape, a4.shape, a5.shape, a6.shape)

(1728, 4) (1728, 4) (1728, 4) (1728, 3) (1728, 3) (1728, 3)


In [55]:
from sklearn.preprocessing import LabelEncoder

In [56]:
lab = LabelEncoder()

In [57]:
y = lab.fit_transform(y)

In [58]:
df.shape

(1728, 21)

In [59]:
df = df.iloc[:,1:] #to avoid the dummy variable trap
df.shape

(1728, 20)

In [60]:
df.head()

buy_low  buy_med  buy_vhigh  mainte_high  mainte_low  mainte_med  \
0        0        0          1            0           0           0   
1        0        0          1            0           0           0   
2        0        0          1            0           0           0   
3        0        0          1            0           0           0   
4        0        0          1            0           0           0   

   mainte_vhigh  doors_2  doors_3  doors_4  doors_5more  persons_2  persons_4  \
0             1        1        0        0            0          1          0   
1             1        1        0        0            0          1          0   
2             1        1        0        0            0          1          0   
3             1        1        0        0            0          1          0   
4             1        1        0        0            0          1          0   

   persons_more  lug_big  lug_med  lug_small  safety_high  safety_low  \
0             0        0        0          1            0           1   
1             0        0        0          1            0           0   
2             0        0        0          1            1           0   
3             0        0        1          0            0           1   
4             0        0        1          0            0           0   

   safety_med  
0           0  
1           1  
2           0  
3           0  
4           1

In [61]:
X = df.values

In [62]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [63]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [64]:
X_train = X_train.astype('float64')
X_test = X_test.astype('float64')
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [65]:
model = LogisticRegression(multi_class='auto', solver='lbfgs', max_iter=150)

In [66]:
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=150, multi_class='auto',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [67]:
model.score(X_train,y_train)

0.9384949348769899

In [68]:
model.score(X_test, y_test)

0.930635838150289

In [69]:
from sklearn.metrics import classification_report, confusion_matrix

In [70]:
print(classification_report(y_test, model.predict(X_test)))

              precision    recall  f1-score   support

           0       0.89      0.82      0.86        83
           1       0.62      0.91      0.74        11
           2       0.96      0.97      0.97       235
           3       0.94      0.94      0.94        17

   micro avg       0.93      0.93      0.93       346
   macro avg       0.86      0.91      0.88       346
weighted avg       0.93      0.93      0.93       346



In [71]:
print(confusion_matrix(y_test, model.predict(X_test)))

[[ 68   6   9   0]
 [  0  10   0   1]
 [  7   0 228   0]
 [  1   0   0  16]]


In [72]:
from sklearn.metrics import accuracy_score

In [73]:
print(accuracy_score(y_test, model.predict(X_test)))

0.930635838150289


In [74]:
X_test.shape

(346, 20)

In [75]:
svm = SVC(kernel='poly')

In [76]:
svm.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='poly', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [77]:
print(classification_report(y_test, svm.predict(X_test)))

              precision    recall  f1-score   support

           0       0.99      0.92      0.95        83
           1       0.56      0.91      0.69        11
           2       1.00      1.00      1.00       235
           3       0.94      0.88      0.91        17

   micro avg       0.97      0.97      0.97       346
   macro avg       0.87      0.93      0.89       346
weighted avg       0.98      0.97      0.97       346



In [78]:
print(confusion_matrix(y_test, svm.predict(X_test)))

[[ 76   7   0   0]
 [  0  10   0   1]
 [  0   0 235   0]
 [  1   1   0  15]]


In [79]:
print(accuracy_score(y_test, model.predict(X_test)))

0.930635838150289


In [81]:
from sklearn.model_selection import GridSearchCV

In [98]:
param_grid = {"kernel":['poly','rbf','linear'],
             "C":np.linspace(0.1,1,10),
             "gamma":np.linspace(0,1,10)}

In [104]:
gs = GridSearchCV(estimator=svm, param_grid=param_grid, cv=10, scoring=['accuracy'], n_jobs=-1, verbose=1, refit=False)

In [105]:
gs.fit(X_train,y_train)

Fitting 10 folds for each of 300 candidates, totalling 3000 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    4.8s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:   17.6s
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:   38.0s
[Parallel(n_jobs=-1)]: Done 792 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 1242 tasks      | elapsed:  1.7min
[Parallel(n_jobs=-1)]: Done 1792 tasks      | elapsed:  2.6min
[Parallel(n_jobs=-1)]: Done 2442 tasks      | elapsed:  3.5min
[Parallel(n_jobs=-1)]: Done 3000 out of 3000 | elapsed:  4.3min finished


GridSearchCV(cv=10, error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='poly', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid={'kernel': ['poly', 'rbf', 'linear'], 'C': array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]), 'gamma': array([0.     , 0.11111, 0.22222, 0.33333, 0.44444, 0.55556, 0.66667,
       0.77778, 0.88889, 1.     ])},
       pre_dispatch='2*n_jobs', refit=False, return_train_score='warn',
       scoring=['accuracy'], verbose=1)

In [110]:
gs.estimator

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='poly', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)