# Churn Modelling using ANN
You can read about churn modelling and why it is necessary to do so [here](https://www.datascience.com/blog/what-is-a-churn-analysis-and-why-is-it-valuable-for-business).                     
In this notebook we will predict whether the customer will stay in the Bank or leave. Following are the tasks that we are going to perform.
1. Data Cleaning
2. Data Description
3. Data Visualization
4. Data Encoding
5. Handle Categorical Data 
6. Standerdization
7. ANN Model
8. ANN with Cross Validation
9. ANN with Dropout regularization
10. Tuning the Hyper parameters using GridsearchCV

# Artificial Neural Networks
Here I am providing some study material.
1. [Basic understanding of ANN](https://www.analyticsvidhya.com/blog/2014/10/ann-work-simplified/)
2. [Working of Neural Networks](https://towardsdatascience.com/understanding-neural-networks-what-how-and-why-18ec703ebd31)
3. [Backpropagation](https://en.wikipedia.org/wiki/Backpropagation)
4. [Activation Functions in NN](https://towardsdatascience.com/activation-functions-and-its-types-which-is-better-a9a5310cc8f)

In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
dataset = pd.read_csv(r'E:\Machine Learning A-Z Template Folder\Churnn_Modelling.csv')

In [3]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [4]:
dataset.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [5]:
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [6]:
X.shape, y.shape

((10000, 10), (10000,))

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
lab_x= LabelEncoder()
X[:, 1] = lab_x.fit_transform(X[:, 1])

In [8]:
lab_x2= LabelEncoder()
X[:, 2] = lab_x.fit_transform(X[:, 2])

In [9]:
one_hot = OneHotEncoder(categorical_features=[1])
X = one_hot.fit_transform(X).toarray()

C:\Users\Siam Cheema\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Siam Cheema\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [10]:
#avoiding dumy variables trap
X = X[:,1:]

In [11]:
X.shape

(10000, 11)

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = .2, random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
#Making ANN
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [15]:
#initialising ANN
classifier = Sequential()

In [16]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation='relu', input_dim=11))
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation='relu'))
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
#softmax for more than two output categories

Instructions for updating:
Colocations handled automatically by placer.


In [17]:
#Compiling the ANN
# loss function is same as in Logistic regression
classifier.compile(optimizer = 'adam', loss= 'binary_crossentropy', metrics=['accuracy'])

In [18]:
classifier.fit(X_train, y_train, batch_size= 10, epochs=100)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8000/8000 [==============================] - 2s 266us/step - loss: 0.5079 - acc: 0.7954
Epoch 2/100
8000/8000 [==============================] - 2s 196us/step - loss: 0.4305 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 209us/step - loss: 0.4262 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 2s 193us/step - loss: 0.4223 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 2s 191us/step - loss: 0.4194 - acc: 0.8129
Epoch 6/100
8000/8000 [==============================] - 2s 196us/step - loss: 0.4167 - acc: 0.8255
Epoch 7/100
8000/8000 [==============================] - 2s 199us/step - loss: 0.4148 - acc: 0.8262
Epoch 8/100
8000/8000 [==============================] - 1s 187us/step - loss: 0.4133 - acc: 0.8287
Epoch 9/100
8000/8000 [==============================] - 1s 185us/step - loss: 0.4120 - acc: 0.8309
Epoch 10/100
8000/8000 [============================

In [19]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred[:10]

array([[False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True]])

In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [21]:
cm

array([[1542,   53],
       [ 267,  138]], dtype=int64)

In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.97      0.91      1595
           1       0.72      0.34      0.46       405

   micro avg       0.84      0.84      0.84      2000
   macro avg       0.79      0.65      0.68      2000
weighted avg       0.83      0.84      0.82      2000



Evaluating the ANN

In [23]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [24]:
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation='relu', input_dim=11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation='relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss= 'binary_crossentropy', metrics=['accuracy'])
    return classifier  

In [25]:
classifier = KerasClassifier(build_fn=build_classifier, batch_size=10, nb_epoch=100)
accuracies = cross_val_score(estimator=classifier, X = X_train, y=y_train, cv=10, n_jobs=-1)

In [26]:
accuracies

array([0.78625   , 0.79      , 0.8       , 0.7825    , 0.81625   ,
       0.81      , 0.7875    , 0.79375   , 0.79875   , 0.79499999])

In [27]:
mean = accuracies.mean()
variance = accuracies.std()

In [28]:
mean

0.7959999969601632

In [29]:
variance

0.010105690620981692

# Improving the ANN with regularization
You can study about Dropout regularization [here](https://machinelearningmastery.com/dropout-regularization-deep-learning-models-keras/) and how it helps the model in avoiding overfitting

In [30]:
from keras.layers import Dropout

In [31]:
classifier = Sequential()
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation='relu', input_dim=11))
classifier.add(Dropout(rate=0.1))
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation='relu'))
classifier.add(Dropout(rate=0.1))
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
classifier.compile(optimizer = 'adam', loss= 'binary_crossentropy', metrics=['accuracy'])
#softmax for more than two output categories

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [32]:
classifier.fit(X_train,y_train, batch_size=10, epochs=100)

Epoch 1/100
8000/8000 [==============================] - 2s 306us/step - loss: 0.4838 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 2s 220us/step - loss: 0.4359 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 218us/step - loss: 0.4349 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 2s 221us/step - loss: 0.4292 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 2s 233us/step - loss: 0.4280 - acc: 0.8076
Epoch 6/100
8000/8000 [==============================] - 2s 211us/step - loss: 0.4250 - acc: 0.8219
Epoch 7/100
8000/8000 [==============================] - 2s 209us/step - loss: 0.4251 - acc: 0.8255
Epoch 8/100
8000/8000 [==============================] - 2s 209us/step - loss: 0.4230 - acc: 0.8275
Epoch 9/100
8000/8000 [==============================] - 2s 204us/step - loss: 0.4207 - acc: 0.8302
Epoch 10/100
8000/8000 [==============================] - 2s 229us/step - loss: 0.4245 - acc: 0.8312

**Hyper Parameters Tuning**

In [33]:
from sklearn.model_selection import GridSearchCV

In [36]:
def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation='relu', input_dim=11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation='relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss= 'binary_crossentropy', metrics=['accuracy'])
    return classifier

In [37]:
classifier = KerasClassifier(build_fn=build_classifier)
parameters = {'batch_size':[25, 32],
             'epochs':[100,500],
             'optimizer':['adam','rmsprop']}
grid_search = GridSearchCV(estimator=classifier,param_grid=parameters, scoring='accuracy', cv=10, n_jobs=-1)

In [38]:
grid_search = grid_search.fit(X_train,y_train)

Epoch 1/100
7200/7200 [==============================] - 1s 185us/step - loss: 0.5797 - acc: 0.7946
Epoch 2/100
7200/7200 [==============================] - 1s 91us/step - loss: 0.4341 - acc: 0.7971
Epoch 3/100
7200/7200 [==============================] - 1s 83us/step - loss: 0.4299 - acc: 0.7971
Epoch 4/100
7200/7200 [==============================] - 1s 85us/step - loss: 0.4270 - acc: 0.7971
Epoch 5/100
7200/7200 [==============================] - 1s 86us/step - loss: 0.4242 - acc: 0.7971
Epoch 6/100
7200/7200 [==============================] - 1s 82us/step - loss: 0.4218 - acc: 0.7971
Epoch 7/100
7200/7200 [==============================] - 1s 81us/step - loss: 0.4195 - acc: 0.7971
Epoch 8/100
7200/7200 [==============================] - 1s 84us/step - loss: 0.4180 - acc: 0.8178
Epoch 9/100
7200/7200 [==============================] - 1s 85us/step - loss: 0.4165 - acc: 0.8225
Epoch 10/100
7200/7200 [==============================] - 1s 82us/step - loss: 0.4155 - acc: 0.8240
Epoch 11

In [39]:
grid_search.best_params_

{'batch_size': 25, 'epochs': 500, 'optimizer': 'rmsprop'}

In [40]:
grid_search.best_score_

0.848125

So we have got the final model, which has the following parameters as batch_size of 25, epochs = 500 and optimizer as 'rmsprop'. 