# Overfitting
In this notebook we will see the effect of overfitting using SVM. We will see that our gap between training error and generalization error will be huge as we will increase the degree of Polynomial.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()

In [2]:
from sklearn.datasets import load_breast_cancer

In [3]:
dataset = load_breast_cancer()

In [4]:
df = pd.DataFrame(dataset.data,columns=dataset.feature_names)
df['class'] = dataset.target

In [5]:
df.shape

(569, 31)

In [7]:
df.describe()

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension     ...      worst texture  \
count     569.000000              569.000000     ...         569.000000   
mean        0.181162                0.062798     ...          25.677223   
std         0.027414                0.007060     ...           6.146258   
min         0.106000                0.049960     ...          12.020000   
25%         0.161900                0.057700     ...          21.080000   
50%         0.179200                0.061540     ...          25.410000   
75%         0.195700                0.066120     ...          29.720000   
max         0.304000                0.097440     ...          49.540000   

       worst perimeter   worst area  worst smoothness  worst compactness  \
count       569.000000   569.000000        569.000000         569.000000   
mean        107.261213   880.583128          0.132369           0.254265   
std          33.602542   569.356993          0.022832           0.157336   
min          50.410000   185.200000          0.071170           0.027290   
25%          84.110000   515.300000          0.116600           0.147200   
50%          97.660000   686.500000          0.131300           0.211900   
75%         125.400000  1084.000000          0.146000           0.339100   
max         251.200000  4254.000000          0.222600           1.058000   

       worst concavity  worst concave points  worst symmetry  \
count       569.000000            569.000000      569.000000   
mean          0.272188              0.114606        0.290076   
std           0.208624              0.065732        0.061867   
min           0.000000              0.000000        0.156500   
25%           0.114500              0.064930        0.250400   
50%           0.226700              0.099930        0.282200   
75%           0.382900              0.161400        0.317900   
max           1.252000              0.291000        0.663800   

       worst fractal dimension       class  
count               569.000000  569.000000  
mean                  0.083946    0.627417  
std                   0.018061    0.483918  
min                   0.055040    0.000000  
25%                   0.071460    0.000000  
50%                   0.080040    1.000000  
75%                   0.092080    1.000000  
max                   0.207500    1.000000  

[8 rows x 31 columns]

In [8]:
df.groupby('class').mean()

mean radius  mean texture  mean perimeter   mean area  mean smoothness  \
class                                                                           
0        17.462830     21.604906      115.365377  978.376415         0.102898   
1        12.146524     17.914762       78.075406  462.790196         0.092478   

       mean compactness  mean concavity  mean concave points  mean symmetry  \
class                                                                         
0              0.145188        0.160775             0.087990       0.192909   
1              0.080085        0.046058             0.025717       0.174186   

       mean fractal dimension           ...             worst radius  \
class                                   ...                            
0                    0.062680           ...                21.134811   
1                    0.062867           ...                13.379801   

       worst texture  worst perimeter   worst area  worst smoothness  \
class                                                                  
0          29.318208       141.370330  1422.286321          0.144845   
1          23.515070        87.005938   558.899440          0.124959   

       worst compactness  worst concavity  worst concave points  \
class                                                             
0               0.374824         0.450606              0.182237   
1               0.182673         0.166238              0.074444   

       worst symmetry  worst fractal dimension  
class                                           
0            0.323468                 0.091530  
1            0.270246                 0.079442  

[2 rows x 30 columns]

In [9]:
df['class'].value_counts()

1    357
0    212
Name: class, dtype: int64

In [26]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [27]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0)

In [29]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [30]:
lr = LogisticRegression(solver='lbfgs', max_iter=200,C=1)
lr.fit(X_train,y_train)

LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=200, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [31]:
def print_score(model, X_train, y_train, X_test, y_test, train=True):
    '''
    Taining Performence
    '''
    if train:
        print("Train Result:\n")
        print("Accuracy Score: {0:.4f}\n".format(accuracy_score(y_train, model.predict(X_train))))
        print("Classification Report: \n {} \n".format(classification_report(y_train,model.predict(X_train))))
        print("Confusion Matrix:")
        print(confusion_matrix(y_train, model.predict(X_train)))
        
        res = cross_val_score(model, X_train, y_train, cv=10, scoring='accuracy')
        print("Average Accuracy: \t {0:.4f}".format(np.mean(res)))
        print("Accuracy SD: \t\t {0:.4f}".format(np.std(res)))
    
    elif train == False:
        '''
        Testing Performence
        '''
        print("Test Results:\n")
        print("Accuracy Score: {0:.4f}".format(accuracy_score(y_test, model.predict(X_test))))
        print("Classification Report: \n {} \n".format(classification_report(y_test,model.predict(X_test))))
        print("Confusion Matrix:")
        print(confusion_matrix(y_test, model.predict(X_test)))

In [32]:
print_score(lr, X_train, y_train, X_test, y_test, train=True)

Train Result:

Accuracy Score: 0.9890

Classification Report: 
               precision    recall  f1-score   support

           0       0.99      0.98      0.98       165
           1       0.99      1.00      0.99       290

   micro avg       0.99      0.99      0.99       455
   macro avg       0.99      0.99      0.99       455
weighted avg       0.99      0.99      0.99       455
 

Confusion Matrix:
[[161   4]
 [  1 289]]
Average Accuracy: 	 0.9781
Accuracy SD: 		 0.0198


In [33]:
print_score(lr, X_train, y_train, X_test, y_test, train=False)

Test Results:

Accuracy Score: 0.9649
Classification Report: 
               precision    recall  f1-score   support

           0       0.96      0.96      0.96        47
           1       0.97      0.97      0.97        67

   micro avg       0.96      0.96      0.96       114
   macro avg       0.96      0.96      0.96       114
weighted avg       0.96      0.96      0.96       114
 

Confusion Matrix:
[[45  2]
 [ 2 65]]


In [35]:
from sklearn.svm import SVC
svm = SVC(gamma='scale', kernel='linear')
svm.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [37]:
print_score(svm, X_train, y_train, X_test, y_test, train=True)

Train Result:

Accuracy Score: 0.9890

Classification Report: 
               precision    recall  f1-score   support

           0       0.99      0.98      0.98       165
           1       0.99      1.00      0.99       290

   micro avg       0.99      0.99      0.99       455
   macro avg       0.99      0.99      0.99       455
weighted avg       0.99      0.99      0.99       455
 

Confusion Matrix:
[[161   4]
 [  1 289]]
Average Accuracy: 	 0.9715
Accuracy SD: 		 0.0198


In [38]:
print_score(svm, X_train, y_train, X_test, y_test, train=False)

Test Results:

Accuracy Score: 0.9825
Classification Report: 
               precision    recall  f1-score   support

           0       0.98      0.98      0.98        47
           1       0.99      0.99      0.99        67

   micro avg       0.98      0.98      0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114
 

Confusion Matrix:
[[46  1]
 [ 1 66]]


In [39]:
from sklearn.svm import SVC
svm = SVC(gamma='scale', kernel='rbf')
svm.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [40]:
print_score(svm, X_train, y_train, X_test, y_test, train=True)

Train Result:

Accuracy Score: 0.9846

Classification Report: 
               precision    recall  f1-score   support

           0       0.99      0.96      0.98       165
           1       0.98      1.00      0.99       290

   micro avg       0.98      0.98      0.98       455
   macro avg       0.99      0.98      0.98       455
weighted avg       0.98      0.98      0.98       455
 

Confusion Matrix:
[[159   6]
 [  1 289]]
Average Accuracy: 	 0.9759
Accuracy SD: 		 0.0153


In [41]:
print_score(svm, X_train, y_train, X_test, y_test, train=False)

Test Results:

Accuracy Score: 0.9825
Classification Report: 
               precision    recall  f1-score   support

           0       1.00      0.96      0.98        47
           1       0.97      1.00      0.99        67

   micro avg       0.98      0.98      0.98       114
   macro avg       0.99      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114
 

Confusion Matrix:
[[45  2]
 [ 0 67]]


In [42]:
from sklearn.svm import SVC
svm = SVC(gamma='scale', kernel='poly', degree=3)
svm.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [43]:
print_score(svm, X_train, y_train, X_test, y_test, train=True)

Train Result:

Accuracy Score: 0.9099

Classification Report: 
               precision    recall  f1-score   support

           0       1.00      0.75      0.86       165
           1       0.88      1.00      0.93       290

   micro avg       0.91      0.91      0.91       455
   macro avg       0.94      0.88      0.90       455
weighted avg       0.92      0.91      0.91       455
 

Confusion Matrix:
[[124  41]
 [  0 290]]
Average Accuracy: 	 0.8923
Accuracy SD: 		 0.0208


In [44]:
print_score(svm, X_train, y_train, X_test, y_test, train=False)

Test Results:

Accuracy Score: 0.9035
Classification Report: 
               precision    recall  f1-score   support

           0       1.00      0.77      0.87        47
           1       0.86      1.00      0.92        67

   micro avg       0.90      0.90      0.90       114
   macro avg       0.93      0.88      0.90       114
weighted avg       0.92      0.90      0.90       114
 

Confusion Matrix:
[[36 11]
 [ 0 67]]


In [45]:
from sklearn.svm import SVC
svm = SVC(gamma='scale', kernel='poly', degree=4)
svm.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=4, gamma='scale', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [46]:
print_score(svm, X_train, y_train, X_test, y_test, train=True)

Train Result:

Accuracy Score: 0.8352

Classification Report: 
               precision    recall  f1-score   support

           0       1.00      0.55      0.71       165
           1       0.79      1.00      0.89       290

   micro avg       0.84      0.84      0.84       455
   macro avg       0.90      0.77      0.80       455
weighted avg       0.87      0.84      0.82       455
 

Confusion Matrix:
[[ 90  75]
 [  0 290]]
Average Accuracy: 	 0.8087
Accuracy SD: 		 0.0392


In [47]:
print_score(svm, X_train, y_train, X_test, y_test, train=False)

Test Results:

Accuracy Score: 0.7719
Classification Report: 
               precision    recall  f1-score   support

           0       0.96      0.47      0.63        47
           1       0.73      0.99      0.84        67

   micro avg       0.77      0.77      0.77       114
   macro avg       0.84      0.73      0.73       114
weighted avg       0.82      0.77      0.75       114
 

Confusion Matrix:
[[22 25]
 [ 1 66]]


As our data is linearly separable as we are increasing the degree of polynomial or using another kernel our model is overfitting.